trigger:
- master

pool:
  name: MyFreePool
  demands:
    - agent -equals agent2


stages:
  - stage: QA
    jobs:
      - job: QAJOB 
  - stage: TEST1
    dependsOn : QA
    jobs:
      - job: TESTJOB1
  - stage: TEST
    dependsOn : 
    - TEST1
    - PRODUCTION 
    jobs:
      - job: TESTJOB 
  - stage: PRODUCTION
    dependsOn : QA
    jobs:
      - job: PRODUCTIONJOB 
        
