trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: QA
    jobs:
      - job: QAJOB 
  - stage: TEST
    jobs:
      - job: TESTJOB 
  - stage: PRODUCTION
    jobs:
      - job: PRODUCTIONJOB 
        
