trigger:
- master

pool:
  name: MyFreePool
  demands:
    - agent -equals agent2


stages:
  - stage: QA
    jobs:
      - job: QAJOB 
  - stage: TEST1
    dependsOn : []
    jobs:
      - job: TESTJOB1
  - stage: TEST
    jobs:
      - job: TESTJOB 
  - stage: PRODUCTION
    
    jobs:
      - job: PRODUCTIONJOB 
        
